#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("Version = ", np.__version__)
print()
np.show_config()

Version =  1.22.4

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
zeroVector = np.zeros(10)
print(zeroVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print("Size of array = %d bytes" % zeroVector.nbytes)

Size of array = 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vectorWithUnit = np.zeros(10)
vectorWithUnit[4] = 1
print(vectorWithUnit)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vectorRange = np.arange(10, 50)
print(vectorRange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vectorRange = vectorRange[::-1]
print(vectorRange)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
indexsNotNull = np.nonzero([1,2,0,0,4,0])
print(indexsNotNull)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
identityMatrix = np.eye(3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
randomArray = np.random.random((3,3,3))
print(randomArray)

[[[0.04267425 0.43868039 0.20686662]
  [0.21578021 0.4793274  0.4576996 ]
  [0.1822031  0.84589795 0.61394807]]

 [[0.35943363 0.1810462  0.72491545]
  [0.00680407 0.8180828  0.25027893]
  [0.63889839 0.84440109 0.57418982]]

 [[0.98661929 0.03020655 0.53811545]
  [0.6502032  0.41483421 0.05303096]
  [0.08165713 0.71678969 0.27492167]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
randomArray = np.random.random((10, 10))
minValue, maxValue = randomArray.min(), randomArray.max()
print("min =", minValue, ", max =", maxValue)

min = 0.00689445560191182 , max = 0.9937405350242361


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
randomArray = np.random.random(30)
mean = randomArray.mean()
print(mean)

0.5370167764674506


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
onesArray = np.ones((5, 5))
onesArray[1:-1, 1:-1] = 0
print(onesArray)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
onesArray = np.ones((5,5))
onesArray = np.pad(onesArray, pad_width=1, mode='constant', constant_values=0)
print(onesArray)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
matrix = np.diag(np.arange(1, 5), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
matrix = np.zeros((5,5),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
chessMatrix = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))
print(chessMatrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
randomArray = np.random.random((5, 5))
randomArray = (randomArray - randomArray.mean()) / randomArray.std()
print(randomArray)

[[ 2.03431579  0.67407877  1.18603098  0.9082765  -1.12335546]
 [-0.23262716  1.61671528 -0.94704276 -0.70963057 -1.30824335]
 [ 1.28971764 -0.33676251 -1.50001278  1.11716588  0.73069717]
 [-0.88159913  0.14781357 -0.75227804  0.85203231 -0.69936919]
 [ 0.44005982 -1.43300245 -0.21797319 -0.22168427 -0.63332284]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([('r', np.ubyte),
                 ('g', np.ubyte),
                 ('b', np.ubyte),
                 ('a', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
multiMatrix = np.random.random((5, 3)) @ np.random.random((3, 2))
print(multiMatrix)
multiMatrix = np.ones((5, 3)) @ np.ones((3, 2))
print(multiMatrix)

[[0.50978527 0.87278691]
 [1.11572189 1.47062596]
 [1.03038326 1.128432  ]
 [0.4217931  0.74016656]
 [0.52907448 0.91036508]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
array = np.arange(11)
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(5)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-29-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-29-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
matrix = np.random.uniform(-10,+10,10)
print(matrix)
print(np.ceil(matrix))

[ 9.37338008 -5.1485233  -4.68475549 -0.31510203 -5.16686239 -8.53116076
  7.3685933  -6.6429115  -8.01139668 -3.48146076]
[10. -5. -4. -0. -5. -8.  8. -6. -8. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
print("array 1 =", array1)
print("array 2 =", array2)

print("common =", np.intersect1d(array1, array2))

array 1 = [4 5 9 6 2 3 2 6 9 7]
array 2 = [5 3 7 0 1 3 3 2 3 7]
common = [2 3 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday =", yesterday)
print("today =", today)
print("tomorrow =", tomorrow)

yesterday = 2023-06-05
today = 2023-06-06
tomorrow = 2023-06-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
dateJuly = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dateJuly)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones(3)*1/5
B = np.ones(3)*14.5
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.47, -1.47, -1.47])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
randomArray = np.random.uniform(0,10,5)
print('randomArray =', randomArray)
print(randomArray // 1)
print(np.floor(randomArray))
print(randomArray.astype(int))
print(np.trunc(randomArray))

randomArray = [9.18942686 8.94106104 2.82532498 8.23684154 1.64851654]
[9. 8. 2. 8. 1.]
[9. 8. 2. 8. 1.]
[9 8 2 8 1]
[9. 8. 2. 8. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
randomMatrix = np.random.randint(0, 5, 25).reshape((5, 5))
print(randomMatrix)

[[0 0 1 0 2]
 [2 3 0 4 1]
 [0 4 2 2 2]
 [2 3 0 4 1]
 [1 0 3 4 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def generator():
    for x in range(10):
        yield x
generateArray = np.fromiter(generator(),dtype=int,count=-1)
print(generateArray)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
vector = np.linspace(0,1,11,endpoint=False)
print(vector)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
randomSortVector = np.random.randint(0, 100, 10)
randomSortVector.sort()
print(randomSortVector)

[ 6 23 37 39 41 42 58 59 63 71]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
vector = np.arange(10)
print(np.add.reduce(vector))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
A = np.random.randint(0, 100, 10)
B = np.random.randint(0, 100, 10)
print("A =", A)
print("B =", B)
print(np.array_equal(A, B))

A = [68 42 79 27 93 40 50 24 25 89]
B = [97 94  7 24  4 56 44 66 75 54]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
readArray = np.zeros(10)
readArray.flags.writeable = False
readArray[5] = 811

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
decart = np.random.random((10,2))
X,Y = decart[:,0], decart[:,1]
R = np.sqrt(X**2+Y**2)
fi = np.arctan2(Y,X)
print(R)
print(fi)

[0.98072609 0.96164137 0.98458686 0.79647167 0.9286661  0.785253
 1.0469698  0.761089   0.72812119 0.9098905 ]
[0.10951268 1.41547903 0.21933862 0.57117305 0.02939176 0.1342326
 0.55494499 0.2411732  1.22228648 0.27034808]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
randomVector = np.random.randint(0, 100, 10)
print(randomVector)
randomVector[randomVector.argmax()] = 0
print(randomVector)


[10 44 29 27 31 79 58 83 16 75]
[10 44 29 27 31 79 58  0 16 75]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
coordinates = np.zeros((5,5), [('x',float),('y',float)])
coordinates['x'], coordinates['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(coordinates)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
X = np.random.randint(1, 100, 10)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.01398601 -0.06896552 -0.08695652 -0.01652893 -0.02898551
  -0.01273885 -0.01652893 -0.02469136 -0.22222222]
 [ 0.0141844  -2.          0.01769912  0.01680672  0.0952381   0.02739726
  -0.13333333  0.0952381   0.03278689  0.01503759]
 [ 0.07407407 -0.0173913  -2.          0.4        -0.02150538 -0.04878049
  -0.01550388 -0.02150538 -0.03773585  0.10526316]
 [ 0.0952381  -0.01652893 -0.28571429 -2.         -0.02020202 -0.04255319
  -0.01481481 -0.02020202 -0.03389831  0.15384615]
 [ 0.01680672 -0.08695652  0.02197802  0.02061856 -2.          0.03921569
  -0.05405405 -2.          0.05128205  0.01801802]
 [ 0.02985075 -0.02666667  0.05128205  0.04444444 -0.03773585 -2.
  -0.02247191 -0.03773585 -0.15384615  0.03389831]
 [ 0.01290323  0.15384615  0.01574803  0.01503759  0.05714286  0.02298851
  -2.          0.05714286  0.02666667  0.01360544]
 [ 0.01680672 -0.08695652  0.02197802  0.02061856 -2.          0.03921569
  -0.05405405 -2.          0.05128205  0.01801802]
 [ 0.025

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [49]:
for dtype in [np.int8, np.int32, np.int64]:
   print(dtype)
   print("min = ", np.iinfo(dtype).min)
   print("max =" ,np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(dtype)
   print("min = ", np.finfo(dtype).min)
   print("max = ", np.finfo(dtype).max)

<class 'numpy.int8'>
min =  -128
max = 127
<class 'numpy.int32'>
min =  -2147483648
max = 2147483647
<class 'numpy.int64'>
min =  -9223372036854775808
max = 9223372036854775807
<class 'numpy.float32'>
min =  -3.4028235e+38
max =  3.4028235e+38
<class 'numpy.float64'>
min =  -1.7976931348623157e+308
max =  1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [50]:
np.set_printoptions(threshold=float("inf"), linewidth = 1000)
vector = np.ones((30,37))
print(vector)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
vector = np.random.randint(0, 100, 10)
value = np.random.uniform(0,100)
index = (np.abs(vector-value)).argmin()
print(vector)
print(value)
print(vector[index])

[81 18 41 89  0 45 64 23 24 93]
29.86599958240932
24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [52]:
structure = np.zeros(10, [ ('position', [ ('x', float, 1),
                                          ('y', float, 1)]),
                           ('color',    [ ('r', float, 1),
                                          ('g', float, 1),
                                          ('b', float, 1)])])
print(structure)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-52-03833951ef48>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  structure = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.76143172 0.84120284 0.8472086  0.81264995 0.73056319 0.97364258 0.20099053 0.47109659 0.22369831 0.51679416 0.87540459 0.65547769 0.08657595 0.197942   0.37946388 0.45260541 0.62116355 0.49436449 0.12983621 0.39390555 0.50084997 0.37010185 0.32779273 0.41730406 0.60119597 0.56997351 0.40616351 0.67121846 0.63555561 0.53121826 0.89346122 0.91910588 0.41889293 0.60890065 0.10101289 0.33735458 0.86110182 0.43125391 0.42742355 0.19934544 0.45552488 0.86298815 0.57396711 0.2330308  0.37051657 0.47019527 0.74958826 0.8411283  0.35908259 0.87017495 0.2226681  0.60578422 0.66498657 0.41127727 0.41330356 0.57484405 0.36380828 0.45989365 0.60389914 0.64033465 0.45369608 0.11044761 0.2425765  0.20412752 0.26358421 0.63786259 0.39324638 0.60161333 0.50073192 0.48162349 0.92431608 0.67078684 0.75309827 0.7353332  0.41203827 0.82718043 0.58818018 0.28985571 0.55324745 0.83286565 0.3317011  0.32727258 0.50981693 0.4888255  0.40029783 0.96598997 0.44720359 0.7375995  0.81209803
  0.5620

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
vectorFloat = (np.random.randint(1, 100, 10)).astype(np.float32)
vectorInt = vectorFloat.view(np.int32)
vectorInt[:] = vectorFloat # новое представление тех же данных
print(vectorFloat)
print(vectorInt)

[4.20e-44 2.66e-44 5.04e-44 1.29e-43 1.40e-45 1.19e-43 1.40e-44 1.08e-43 5.61e-45 1.30e-43]
[30 19 36 92  1 85 10 77  4 93]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
vectorFromFile = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(vectorFromFile)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-55-663af6a13fb1>:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  vectorFromFile = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
matrix = np.arange(6).reshape(2,3)
for index, value in np.ndenumerate(matrix):
    print(index, value)
print("--------")
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
--------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
n = 5
p = 10
matrix = np.zeros((n,n))
np.put(matrix, np.random.choice(range(n*n), p, replace=False), 5)
print(matrix)

[[0. 0. 0. 0. 0.]
 [5. 5. 0. 0. 0.]
 [0. 0. 0. 5. 5.]
 [5. 5. 5. 5. 0.]
 [0. 5. 0. 5. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1, keepdims=True)

print(Y)

[[-0.19658215 -0.28525261 -0.07005731 -0.32022661 -0.30767031 -0.0801695   0.5752843  -0.18801297  0.50579076  0.36689641]
 [-0.31132916  0.08276748  0.25040123  0.1501778  -0.42557027  0.05208106  0.17599149 -0.053948   -0.23562474  0.31505311]
 [-0.23765666 -0.31778252  0.10583539 -0.32914815  0.48146158  0.10754611  0.4325105  -0.06725512 -0.05624472 -0.11926641]
 [ 0.01018732 -0.28756723  0.06315195  0.12607954  0.59532645  0.31964932 -0.33305813 -0.0159325  -0.08684548 -0.39099125]
 [ 0.41026729  0.28929581 -0.43553901  0.36115895 -0.18426615 -0.09445809  0.42659466 -0.46417261 -0.47403433  0.16515347]]


#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
matrix = np.random.randint(0,10,(3,3))
print(matrix)
print("----------")
print(np.sort(matrix, axis=0))

[[0 7 3]
 [5 3 2]
 [0 0 6]]
----------
[[0 0 2]
 [0 3 3]
 [5 7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
matrix = np.random.randint(0,2,(3,3))
print(matrix)
print("----------")
print((~matrix.any(axis=0)).any())

[[0 1 1]
 [0 1 1]
 [1 1 0]]
----------
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
matrix = np.random.uniform(0,1,10)
value = 0.7
nearest = matrix.flat[np.abs(matrix - value).argmin()]
print(matrix)
print(nearest)

[0.39994865 0.57839356 0.15974448 0.41460332 0.01894819 0.21650039 0.07073267 0.42076112 0.63416542 0.09445079]
0.6341654184820251


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [65]:
matrix = np.ones(10)
another = np.random.randint(0,len(matrix),20)
matrix += np.bincount(another, minlength=len(matrix))
print(matrix)

[3. 2. 1. 6. 2. 1. 2. 6. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [66]:
X = [x for x in range(10)]
I = [y for y in range(1, 11, 1)]
F = np.bincount(I,X)
print(F)

[0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [67]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
A = np.random.randint(0,10,(6,2,1,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[11 21]
 [27  5]
 [15 19]
 [19 10]
 [24 21]
 [20 15]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.44356683 0.57128529 0.4431181  0.4749183  0.57396161 0.52039355 0.42158725 0.63678085 0.59599722 0.5122715 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
A = np.random.uniform(0,1,(4,4))
B = np.random.uniform(0,1,(4,4))

print(np.diag(np.dot(A, B)))

[0.87370214 0.66985392 1.53656131 0.37749249]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
matrix = np.array([1,2,3,4,5])
nz = 3
matrix0 = np.zeros(len(matrix) + (len(matrix)-1)*(nz))
matrix0[::nz+1] = matrix
print(matrix0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [72]:
A = np.ones((5,5,3))
B = 5*np.ones((5,5))
print(A * B[:,:,None])

[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


#### 72. How to swap two rows of an array? (★★★)

In [73]:
A = np.arange(25).reshape(5,5)
A[[0,2]] = A[[2,0]]
print(A)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  8) ( 0, 25) ( 8, 25) ( 9, 14) ( 9, 85) (14, 23) (14, 37) (14, 85) (22, 24) (22, 29) (23, 24) (23, 37) (23, 40) (24, 29) (24, 40) (31, 38) (31, 84) (32, 65) (32, 93) (34, 58) (34, 74) (36, 39) (36, 88) (38, 84) (39, 88) (58, 74) (65, 93) (66, 94) (66, 97) (94, 97)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [76]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(22)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
matrix = rolling(np.arange(10), 3)
print(matrix)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [78]:
Z = np.random.randint(0,2,10)
print(np.logical_not(Z, out=Z))
print("-------------------------------------")
Z = np.random.uniform(-1.0,1.0,10)
print(np.negative(Z, out=Z))

[0 1 0 1 0 1 0 0 0 0]
-------------------------------------
[-0.9118932  -0.90251512  0.55691616 -0.96259565 -0.74652845  0.16524808  0.00115336 -0.8255589  -0.9795047  -0.53368161]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [79]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.74959675 2.74447612 5.12477409 2.14572087 4.21396771 0.76605918 5.36151206 5.51929626 0.57709181 4.19615457]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [80]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.50840132  1.56769887 10.06549223  7.6987821   2.55490621  6.51625918 11.17081587 15.86665544  1.05470804  7.87424337]
 [ 3.42069656  4.9720802   0.51751018  3.78997947  4.88217903  7.46912541  0.91587958  3.78202665 10.68345555  5.76887033]
 [10.23060455  0.16494071  0.07807374  3.867055    2.00625604  1.2773743   7.0735294   3.61989425  9.41383331  9.74805663]
 [ 3.97706935  5.97180907  2.9800511   8.40764575  3.51619515  9.77096411  7.88432182 11.13759566  7.87122636  0.67347026]
 [ 3.0480319   8.45308861 11.35205626  6.86303118  8.39572036  5.43055722  3.76542146  2.13652033  1.78853729  0.791225  ]
 [ 2.09225455  6.72614405 10.41746155  4.97573849  7.00601331  3.58991152  2.2684321   3.32588659  0.68987636  0.88421842]
 [ 0.62066667  6.4766188  11.80170393  3.37693187  7.62173095  2.85887807  0.2433178   6.00581466  1.82832744  3.300949  ]
 [ 0.40324898  3.75592855  2.31825833  4.36164261  2.73319436  6.83950784  3.15176808  6.53931038  8.05046617  2.38968435]
 [ 2.13488031  5

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [81]:
Z = np.random.randint(0,100,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[60 55 82 82 97 83  0 55 25 63]
 [73 11 85 93 73  6 21  7 78 37]
 [14 59 70 18 59 91 54 61 17 91]
 [88  8 33 90 12 99 97 55 41 18]
 [74 21 90 30 30 84 24 98 46 13]
 [17 43 89  9 83 69  6 70 57 82]
 [38 19 64 37 31 52 49 43 82 30]
 [42 59 44 30 62 28 52 77 39 43]
 [22  9 15 69 60 13 56 43 41 47]
 [84 32 80 18 89 77 43  1 57 88]]
[[ 0  0  0  0  0]
 [ 0 60 55 82 82]
 [ 0 73 11 85 93]
 [ 0 14 59 70 18]
 [ 0 88  8 33 90]]


<ipython-input-81-93a85e3becaf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [82]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [84]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [85]:
Z = np.random.randint(0,10,10)
print(Z)
print(np.bincount(Z).argmax())

[8 5 5 3 9 8 4 3 9 9]
9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [86]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 3]
   [3 3 1]
   [0 1 1]]

  [[2 3 3]
   [3 1 0]
   [1 1 0]]

  [[3 3 4]
   [1 0 4]
   [1 0 1]]

  [[3 4 3]
   [0 4 1]
   [0 1 4]]

  [[4 3 3]
   [4 1 0]
   [1 4 2]]

  [[3 3 0]
   [1 0 4]
   [4 2 3]]

  [[3 0 4]
   [0 4 3]
   [2 3 1]]

  [[0 4 0]
   [4 3 0]
   [3 1 2]]]


 [[[3 3 1]
   [0 1 1]
   [4 4 2]]

  [[3 1 0]
   [1 1 0]
   [4 2 0]]

  [[1 0 4]
   [1 0 1]
   [2 0 1]]

  [[0 4 1]
   [0 1 4]
   [0 1 3]]

  [[4 1 0]
   [1 4 2]
   [1 3 4]]

  [[1 0 4]
   [4 2 3]
   [3 4 1]]

  [[0 4 3]
   [2 3 1]
   [4 1 4]]

  [[4 3 0]
   [3 1 2]
   [1 4 1]]]


 [[[0 1 1]
   [4 4 2]
   [2 0 3]]

  [[1 1 0]
   [4 2 0]
   [0 3 4]]

  [[1 0 1]
   [2 0 1]
   [3 4 1]]

  [[0 1 4]
   [0 1 3]
   [4 1 3]]

  [[1 4 2]
   [1 3 4]
   [1 3 1]]

  [[4 2 3]
   [3 4 1]
   [3 1 0]]

  [[2 3 1]
   [4 1 4]
   [1 0 0]]

  [[3 1 2]
   [1 4 1]
   [0 0 0]]]


 [[[4 4 2]
   [2 0 3]
   [4 4 2]]

  [[4 2 0]
   [0 3 4]
   [4 2 0]]

  [[2 0 1]
   [3 4 1]
   [2 0 0]]

  [[0 1 3]
   [4 1 3]
   [0 0 1]]

  [[1 3 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [87]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 12 13 13  6]
 [12  7  6 18 16]
 [13  6  2 42 10]
 [13 18 42  2  6]
 [ 6 16 10  6  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [88]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [89]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [90]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(20,20))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [91]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [93]:
Z = np.array([("bla", 1.65, 36),
              ("foo", 35.768, 72)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'bla',  1.65 , 36) (b'foo', 35.768, 72)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(2e6))

print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [96]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [97]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 1 1]
 [4 0 3]
 [0 0 1]
 [0 2 0]
 [0 2 0]
 [3 2 1]
 [4 3 0]
 [1 2 3]
 [3 3 4]
 [2 1 0]]
[[2 1 1]
 [4 0 3]
 [0 0 1]
 [0 2 0]
 [0 2 0]
 [3 2 1]
 [4 3 0]
 [1 2 3]
 [3 3 4]
 [2 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [98]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [99]:
Z = np.random.randint(0,10,(6,3))
print(Z)
print("----------")
uZ = np.unique(Z, axis=0)
print(uZ)

[[3 1 7]
 [4 7 7]
 [2 0 3]
 [9 8 8]
 [5 9 8]
 [6 6 1]]
----------
[[2 0 3]
 [3 1 7]
 [4 7 7]
 [5 9 8]
 [6 6 1]
 [9 8 8]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [100]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A))     # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

6.4028197281305665
[0.00640571 0.24977641 0.1863289  0.61857961 0.04285593 0.0475365  0.51877886 0.44923635 0.23806304 0.23757107]
2.5951323871110334
[[0.00640571 0.55657763 0.17475237 0.66092072 0.03517475 0.07217434 0.69981845 0.59459218 0.178419   0.24807096]
 [0.0028747  0.24977641 0.07842396 0.29660266 0.01578544 0.03238982 0.31405887 0.26683627 0.08006944 0.11132728]
 [0.00683006 0.59344832 0.1863289  0.70470365 0.03750491 0.07695556 0.74617818 0.63398116 0.19023843 0.26450451]
 [0.00599534 0.52092115 0.16355706 0.61857961 0.03292132 0.06755058 0.65498541 0.55650034 0.1669888  0.23217859]
 [0.00780454 0.67811868 0.21291342 0.80524739 0.04285593 0.0879352  0.8526393  0.72443455 0.21738074 0.30224275]
 [0.00421902 0.36658112 0.1150979  0.43530506 0.02316729 0.0475365  0.46092444 0.39161881 0.11751288 0.16338804]
 [0.00474859 0.41259374 0.12954479 0.48994378 0.02607521 0.05350319 0.51877886 0.44077411 0.13226288 0.18389622]
 [0.00483975 0.42051496 0.13203187 0.49935001 0.02657582 0.

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [101]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [102]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [103]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11984524  0.24201915]
